### ISSUE TITLE
dle-rae

### ISSUE THREAD

**Issue by angelcarmona** [GrenderG/uDRAE-sdk#1]
https://github.com/angelcarmona/dle-rae

**Comment by GrenderG** [comment]
¡Hola! Gracias por compartir tu proyecto. Voy a añadirlo, pero sería conveniente que explicases en el `README` cómo funciona internamente lo que has hecho y/o qué llamadas estás haciendo a su server (mas que nada por temas educativos. :stuck_out_tongue_closed_eyes:
